version: "1.0.0.{build}"

platform: Any CPU
configuration: Release

skip_tags: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

init:
  - echo %APPVEYOR_BUILD_VERSION%
    
before_build:
  - nuget restore src/NServiceBus.RabbitMQ.sln -DisableParallelProcessing

build:
  parallel: false
  project: src/NServiceBus.RabbitMQ.sln
  verbosity: minimal
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts

deploy:
  - provider: NuGet
    api_key:
      secure: nyYYvfNcljaFo6s6IBdC3lhqwAKOC9HfQjPguKXoHfgs22MwakH+IeXrM2Xn1uc0
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    on:
      branch: master

matrix:
  fast_finish: true

artifacts:
  - path: '*.nupkg'


test: off

